language: java

jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer 

before_install: chmod +x gradlew
script: ./gradlew clean build --stacktrace

after_success:
- ./gradlew jacocoTestReport coveralls